# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'p1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 780)
        MainWindow.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(0, 10, 961, 51))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(830, 690, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setCheckable(True)
        self.pushButton.setObjectName("pushButton")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(120, 100, 720, 540))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tool1 = QtWidgets.QToolButton(self.tab)
        self.tool1.setGeometry(QtCore.QRect(20, 10, 61, 61))
        self.tool1.setCheckable(False)
        self.tool1.setAutoRepeatDelay(300)
        self.tool1.setObjectName("tool1")
        self.tool2 = QtWidgets.QPushButton(self.tab)
        self.tool2.setGeometry(QtCore.QRect(110, 10, 61, 61))
        self.tool2.setObjectName("tool2")
        self.tool3 = QtWidgets.QPushButton(self.tab)
        self.tool3.setGeometry(QtCore.QRect(200, 10, 61, 61))
        self.tool3.setObjectName("tool3")
        self.tool4 = QtWidgets.QPushButton(self.tab)
        self.tool4.setGeometry(QtCore.QRect(290, 10, 61, 61))
        self.tool4.setObjectName("tool4")
        self.tool5 = QtWidgets.QPushButton(self.tab)
        self.tool5.setGeometry(QtCore.QRect(380, 10, 61, 61))
        self.tool5.setObjectName("tool5")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_2.setGeometry(QtCore.QRect(110, 100, 480, 360))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PMingLiU\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:-2px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:36px; background-color:#f8f9fa;\"><a name=\"tw-target-text\"></a><span style=\" font-family:\'inherit\'; font-size:28px; font-weight:600; color:#202124;\">C</span><span style=\" font-family:\'inherit\'; font-size:28px; font-weight:600; color:#202124;\">hoose the mode you want</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "submit"))
        self.tool1.setText(_translate("MainWindow", "t1"))
        self.tool2.setText(_translate("MainWindow", "t2"))
        self.tool3.setText(_translate("MainWindow", "t3"))
        self.tool4.setText(_translate("MainWindow", "t4"))
        self.tool5.setText(_translate("MainWindow", "t5"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
